const CUSTOMER_USER_STATUSES = ['ACTIVE', 'INACTIVE', 'BLOCKED'];
const CUSTOMER_OTP_TYPES = [
  'PHONE_VERIFICATION',
  'EMAIL_VERIFICATION',
  'LOGIN_OTP',
  'FORGOT_PASSWORD'
];

module.exports = {
  CUSTOMER_USER_STATUSES,
  CUSTOMER_OTP_TYPES
};
