const CUSTOMER_TYPES = ['INDIVIDUAL', 'BUSINESS', 'CORPORATE'];
const CUSTOMER_STATUS = ['ACTIVE', 'INACTIVE', 'BLOCKED'];
const CUSTOMER_VERIFICATION_STATUS = ['PENDING', 'VERIFIED', 'REJECTED'];
const CUSTOMER_ADDRESS_TYPES = ['PICKUP', 'DELIVERY', 'BILLING', 'OTHER'];
const CUSTOMER_DOCUMENT_TYPES = [
  'GST_CERTIFICATE',
  'PAN_CARD',
  'AADHAR_CARD',
  'BUSINESS_LICENSE',
  'OTHER'
];

module.exports = {
  CUSTOMER_TYPES,
  CUSTOMER_STATUS,
  CUSTOMER_VERIFICATION_STATUS,
  CUSTOMER_ADDRESS_TYPES,
  CUSTOMER_DOCUMENT_TYPES
};
