const DRIVER_STATUS = ['ACTIVE', 'INACTIVE', 'SUSPENDED'];
const DRIVER_AVAILABILITY_STATUS = ['ONLINE', 'OFFLINE', 'BUSY'];
const DRIVER_VERIFICATION_STATUS = ['PENDING', 'VERIFIED', 'REJECTED'];
const DRIVER_DOCUMENT_TYPES = [
  'DRIVING_LICENSE',
  'AADHAR_CARD',
  'PAN_CARD',
  'VEHICLE_PERMIT',
  'OTHER'
];

module.exports = {
  DRIVER_STATUS,
  DRIVER_AVAILABILITY_STATUS,
  DRIVER_VERIFICATION_STATUS,
  DRIVER_DOCUMENT_TYPES
};
