const PRICING_RULE_STATUSES = ['ACTIVE', 'INACTIVE'];
const DISTANCE_PROVIDERS = ['HAVERSINE', 'GOOGLE_MAPS', 'OPENROUTESERVICE', 'OPENSTREETMAP'];

module.exports = {
  PRICING_RULE_STATUSES,
  DISTANCE_PROVIDERS
};
