const SHIPMENT_TYPES = ['DOCUMENT', 'PARCEL', 'HOUSEHOLD', 'COMMERCIAL', 'FRAGILE'];
const SHIPMENT_PRIORITIES = ['LOW', 'NORMAL', 'HIGH', 'URGENT'];
const SHIPMENT_STATUSES = [
  'DRAFT',
  'PENDING_ASSIGNMENT',
  'ASSIGNED',
  'DRIVER_ACCEPTED',
  'PICKUP_STARTED',
  'PICKED_UP',
  'IN_TRANSIT',
  'OUT_FOR_DELIVERY',
  'DELIVERED',
  'CANCELLED',
  'FAILED'
];

const SHIPMENT_ASSIGNMENT_TYPES = ['MANUAL', 'AUTO'];
const SHIPMENT_ASSIGNMENT_STATUSES = [
  'PENDING',
  'ASSIGNED',
  'ACCEPTED',
  'REJECTED',
  'COMPLETED',
  'CANCELLED'
];
const SHIPMENT_TRACKING_SOURCES = [
  'SYSTEM',
  'DISPATCH',
  'DRIVER_APP',
  'AUTO_ASSIGNMENT',
  'CUSTOMER_SUPPORT'
];

module.exports = {
  SHIPMENT_TYPES,
  SHIPMENT_PRIORITIES,
  SHIPMENT_STATUSES,
  SHIPMENT_ASSIGNMENT_TYPES,
  SHIPMENT_ASSIGNMENT_STATUSES,
  SHIPMENT_TRACKING_SOURCES
};
