const SHIPMENT_TYPES = ['DOCUMENT', 'PARCEL', 'HOUSEHOLD', 'COMMERCIAL', 'FRAGILE'];
const SHIPMENT_PRIORITIES = ['LOW', 'NORMAL', 'HIGH', 'URGENT'];
const SHIPMENT_STATUSES = [
  'DRAFT',
  'PENDING_ASSIGNMENT',
  'ASSIGNED',
  'PICKUP_STARTED',
  'PICKED_UP',
  'IN_TRANSIT',
  'OUT_FOR_DELIVERY',
  'DELIVERED',
  'CANCELLED',
  'FAILED'
];

module.exports = {
  SHIPMENT_TYPES,
  SHIPMENT_PRIORITIES,
  SHIPMENT_STATUSES
};
