const VEHICLE_TYPES = [
  'Bike',
  'Scooter',
  'Mini Truck',
  'Pickup',
  'Tata Ace',
  '3 Wheeler',
  'Truck',
  'Container'
];

const VEHICLE_STATUS = ['ACTIVE', 'INACTIVE', 'SUSPENDED'];
const VEHICLE_VERIFICATION_STATUS = ['PENDING', 'VERIFIED', 'REJECTED'];
const VEHICLE_AVAILABILITY_STATUS = ['AVAILABLE', 'ASSIGNED', 'MAINTENANCE'];
const VEHICLE_DOCUMENT_TYPES = [
  'RC_BOOK',
  'INSURANCE',
  'PUC',
  'FITNESS_CERTIFICATE',
  'PERMIT',
  'OTHER'
];
const DRIVER_VEHICLE_ASSIGNMENT_STATUS = ['ACTIVE', 'INACTIVE'];

module.exports = {
  VEHICLE_TYPES,
  VEHICLE_STATUS,
  VEHICLE_VERIFICATION_STATUS,
  VEHICLE_AVAILABILITY_STATUS,
  VEHICLE_DOCUMENT_TYPES,
  DRIVER_VEHICLE_ASSIGNMENT_STATUS
};
